CREATE TABLE `EVENTS`(
	`ID_EVENT` INTEGER NOT NULL  AUTO_INCREMENT,
	`TITLE` varchar(255) NOT NULL,
	`STARTSAT`DATETIME DEFAULT NULL,
	`ENDSAT`  DATETIME DEFAULT NULL,
	`COST` INTEGER,
	PRIMARY KEY(`ID_EVENT`)
)
--one to one
CREATE TABLE `CLIENT` (
	`ID_EVENT` INTEGER NOT NULL  AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`SURNAME` VARCHAR(255) NOT NULL,
	`EMAIL` VARCHAR(50),
	`PHONE` VARCHAR(40),
     PRIMARY KEY(`ID_EVENT`),
	 CONSTRAINT `fk_client_id` FOREIGN KEY (`ID_EVENT`) REFERENCES `EVENTS` (`ID_EVENT`)
);
--
table user

one to many user_role

table user_role

table_user one to many event

table name_bussines


