/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zyzakj' at '22.07.16 09:07' with Gradle 2.13
 *
 * @author zyzakj, @date 22.07.16 09:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
